version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
